---
# The main playbook for running cluster information gathering
# It will include sub-playbooks through the roles that
# are listed. Each role must define a tasks/main.yml file
# that will be executed
- hosts: localhost
# Just a single role is defined now to show how it can be done
# we may want to consider breaking up this one ansible project
# into two with one for doing cluster configuration and one for
# gathering info. I'm not sure which makes more sense at this
# point.

  vars:
    log_forwarding_host: "52.116.129.80"
    log_forwarding_port: 4000

  roles:
    - enable_cluster_logging