apiVersion: v1
kind: ResourceQuota
metadata:
  name: ryan-quota
  namespace: ryan-ansible
spec:
  hard:
    pods: '3'
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
